repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-amplicontrim_logo_light.png
    - docs/images/nf-core-amplicontrim_logo_light.png
    - docs/images/nf-core-amplicontrim_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-amplicontrim_logo_light.png
    - docs/images/nf-core-amplicontrim_logo_light.png
    - docs/images/nf-core-amplicontrim_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: core-unit-bioinformatics
  name: amplicontrim
  description: Trimming reads in BAM based on BED file with amplicon regions for Ion
    S5 output.
  author: Kai Horny
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - multiqc
    - fastqc
    - gpu
  is_nfcore: false
