lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-amplicontrim_logo_light.png
    - docs/images/nf-core-amplicontrim_logo_light.png
    - docs/images/nf-core-amplicontrim_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - assets/multiqc_config.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-amplicontrim_logo_light.png
    - docs/images/nf-core-amplicontrim_logo_light.png
    - docs/images/nf-core-amplicontrim_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  included_configs: false
  multiqc_config: false
  nextflow_config: false
  nf_test_content: false
  readme:
    - nextflow_badge
    - nfcore_template_badge
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Kai Horny
  description: Trims BAM files based on amplicon regions from Ion S5 output.
  force: false
  is_nfcore: false
  name: amplicontrim
  org: core-unit-bioinformatics
  outdir: .
  skip_features:
    - github_badges
    - ci
    - test_config
    - nf-test
    - multiqc
    - fastqc
    - nf_core_configs
    - seqera_platform
    - gpu
    - gitpod
    - codespaces
    - vscode
  version: 1.0.0dev
